#!/usr/bin/env ruby

# Verify generated catalog, release, lyric, and sitemap artifacts without
# mutating the working tree.

require "fileutils"
require "open3"
require "pathname"
require "rbconfig"
require "tmpdir"

ROOT = File.expand_path("..", __dir__)
INPUTS = %w[
  music-catalog.json
  music-lyrics.json
  music-release-metadata.json
  music.html
  sitemap.xml
].freeze
GENERATED_ROOT_FILES = %w[music.html sitemap.xml].freeze

def first_difference(expected, actual)
  expected_lines = expected.lines
  actual_lines = actual.lines
  limit = [expected_lines.length, actual_lines.length].max
  index = (0...limit).find { |line| expected_lines[line] != actual_lines[line] }
  return nil unless index

  {
    line: index + 1,
    expected: expected_lines[index]&.chomp,
    actual: actual_lines[index]&.chomp
  }
end

missing_inputs = INPUTS.reject { |path| File.file?(File.join(ROOT, path)) }
unless missing_inputs.empty?
  warn "Cannot verify generated music artifacts; missing: #{missing_inputs.join(", ")}"
  exit 1
end

builder = File.join(ROOT, "scripts", "build_music_pages.rb")
unless File.file?(builder)
  warn "Cannot verify generated music artifacts; missing scripts/build_music_pages.rb"
  exit 1
end

failures = []

Dir.mktmpdir("beareab-generated-check-") do |temporary_root|
  FileUtils.mkdir_p(File.join(temporary_root, "scripts"))
  INPUTS.each do |relative|
    FileUtils.cp(File.join(ROOT, relative), File.join(temporary_root, relative))
  end
  FileUtils.cp(builder, File.join(temporary_root, "scripts", "build_music_pages.rb"))

  stdout, stderr, status = Open3.capture3(
    RbConfig.ruby,
    File.join(temporary_root, "scripts", "build_music_pages.rb")
  )
  unless status.success?
    warn "Generated-artifact builder failed in an isolated directory."
    warn stdout unless stdout.empty?
    warn stderr unless stderr.empty?
    exit status.exitstatus || 1
  end

  expected_paths = GENERATED_ROOT_FILES + Dir.glob(
    File.join(temporary_root, "music", "**", "*.html")
  ).map { |path| Pathname(path).relative_path_from(Pathname(temporary_root)).to_s }
  actual_paths = GENERATED_ROOT_FILES + Dir.glob(
    File.join(ROOT, "music", "**", "*.html")
  ).map { |path| Pathname(path).relative_path_from(Pathname(ROOT)).to_s }

  (expected_paths - actual_paths).sort.each do |relative|
    failures << "#{relative}: generated artifact is missing"
  end
  (actual_paths - expected_paths).sort.each do |relative|
    failures << "#{relative}: obsolete generated artifact is still present"
  end

  (expected_paths & actual_paths).uniq.sort.each do |relative|
    expected = File.binread(File.join(temporary_root, relative))
    actual = File.binread(File.join(ROOT, relative))
    next if expected == actual

    difference = first_difference(expected, actual)
    if difference
      failures << [
        "#{relative}:#{difference.fetch(:line)} is stale",
        "  generated: #{difference.fetch(:expected).inspect}",
        "  checked in: #{difference.fetch(:actual).inspect}"
      ].join("\n")
    else
      failures << "#{relative}: generated bytes differ"
    end
  end
end

if failures.empty?
  puts "Generated music artifacts: PASS"
  exit 0
end

warn "Generated music artifacts: FAIL"
failures.each { |failure| warn failure }
warn "Run `ruby scripts/build_music_pages.rb`, review the output, and rerun the quality gate."
exit 1
